spring:
  application:
    name: redis-cache
  cache:
    type: redis
    redis:
      time-to-live: 60000
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/inventory
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  logging:
    pattern:
      level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 4000ms
management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: w3c
    baggage:
      enabled: true
    enabled: true
  zipkin:
    tracing:
      endpoint: http://localhost:9411/zipkin/api/v2/spans
server:
  port: 8081
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.cache: DEBUG
    org.springframework.data.redis: DEBUG
    com.rodolfo.rediscachepostgresql: DEBUG
    com.fasterxml.jackson: TRACE